### ISSUE TITLE
Async plugins

### ISSUE THREAD

**Issue by ai** [postcss/postcss-plugin-context#3]
We need a async plugins support.

**Comment by ben-eb** [comment]
Good call. Any good plugins that I can do an integration test for? (all plugins I know are synchronous)

**Comment by ai** [comment]
I think webpcss should use async https://github.com/lexich/webpcss

**Comment by ben-eb** [comment]
Didn't have to do anything special for this, postcss-svgo worked out of the box.

https://github.com/postcss/postcss-plugin-context/blob/83dabe1120b0b01225685b522747250a365cef82/test.js#L80-L98
