### ISSUE TITLE
Fixes for CodePen

### ISSUE THREAD

**Issue by ai** [postcss/postcss-plugin-context#4]
CodePen wants to add PostCSS support. But they didn’t want to have a buug checklist with plugins.

So `postcss-plugin-context` is ideal for this solution.

But we need to fix there 2 issues and I think that we need additional block-less API:

``` css
@context autoprefixer;

/* Autoprefixer will be used in entire file */
```

/cc @chriscoyier

**Comment by yisibl** [comment]
Good News!

**Comment by yisibl** [comment]
Maybe used `@import` is better?

``` css
@import "cssnext", "Autoprefixer";
```

Introduce a module in Sass. 

``` sass
@import "CSSShake";
```

cc @MoOx

**Comment by ai** [comment]
@yisibl `import` should be for file import. But maybe we should has `@use autoprefixer` alias?

**Comment by yisibl** [comment]
OK, maybe we need to support the options.

``` css
@use autoprefixer  {
   add: false;
   browsers: > 1%, firefox 32;
}
```

**Comment by ai** [comment]
@yisibl yeap, I thought about options. But many plugins has a functions in options. So it can a solution for every plugin.

But we should think about it. Maybe in next version.

**Comment by yisibl** [comment]
OK

**Comment by MoOx** [comment]
Maybe they should "just" implement a long list that you can check from npm search "postcss-plugins" instead ? (better ux)

**Comment by ben-eb** [comment]
:+1: for the `@use` alias.

**Comment by ai** [comment]
@MoOx I talked to @chriscoyier and long plugins list is not a good solution for them.

**Comment by chriscoyier** [comment]
Thanks for all the help on this team! We're excited to get it into CodePen. 

Is the syntax finalized? `@context` / `@import` / `@use` - I don't have too many opinions... `@import` match the syntax of other preprocessors. I like how you can pass settings with `@use` too, that would be useful for Autoprefixer for our users for sure.

**Comment by ben-eb** [comment]
@chriscoyier We decided not to do `@import` as it collides with file imports and also https://github.com/postcss/postcss-import. I am happy to add `@use` as an alias if you would like it, it makes more sense given your use case.

We're not sure on adding options via a CSS syntax as lots of PostCSS plugins can accept a function in their options. Plus it also collides with the original block scope of this module.

Perhaps we can do some alternative syntax for this?

``` css
@use autoprefixer (browsers: '> 1%, ie 6'; add: false);
```

Again it would mean that we couldn't pass functions to plugins, but it would allow for greater experimentation with the plugin ecosystem within CodePen, which would be a good thing.

**Comment by ai** [comment]
@ben-eb maybe we should use `@context { }` for blocks and `@use` for block-less solution.

Should we use a plugins with parameters in `@use` or context name, defined in `postcss-plugin-context` options?

**Comment by ai** [comment]
@chriscoyier I told yesterdat about this Safe Mode: https://github.com/postcss/postcss#safe-mode

You can test PostCSS’s Safe Mode in [Autoprefixer live demo](http://simevidas.jsbin.com/gufoko/quiet).

**Comment by ben-eb** [comment]
> maybe we should use `@context { }` for blocks and `@use` for block-less solution.

I'm on board with that.

We can potentially modify `result.processor.plugins` to allow users to pass options directly from CSS.

**Comment by ai** [comment]
@ben-eb maybe we should create `postcss-use` with only `@use` support? Becuase if we will use `@use autoprefixer (browsers: '> 1%, ie 6'; add: false);` we will have completly different API.

**Comment by ben-eb** [comment]
Yeah, a separate module could work too. The functionality overlaps quite a bit though, it might make sense to release under a new major version?

**Comment by ai** [comment]
What release do you mean? `postcss-plugin-context` with `@use` or block-less `@context`?

**Comment by ben-eb** [comment]
Block-less context was already released under minor version because it didn't change the API. But we could break that API and release a new major version with `@use`.

**Comment by ai** [comment]
We can do not broke API. `@context contextName` will be used for JS-defined plugins list like we have right now. `@user plugin(opts)` will be use to set plugins with options directly in CSS.

**Comment by ben-eb** [comment]
If we are talking about loading the plugins directly from CSS perhaps we should have a different module. :smile:

**Comment by ai** [comment]
@ben-eb sure, so I didn’t understand what major release you suggested :D.

**Comment by ai** [comment]
@chriscoyier [postcss-use](https://github.com/postcss/postcss-use) is finished by @ben-eb
